# Generated by Django 3.0.7 on 2020-06-15 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0002_auto_20200613_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesandans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qns_ans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
